<form class="form-line" id="<?php echo $this->element->getAttrib('id')?>" action="<?php echo $this->element->getAction()?>" method="post" enctype="multipart/form-data">
<?php echo $this->element->getElement('id')->render();?>
    <fieldset>
        <div>
    		<?php echo $this->element->getElement('firstName')->renderLabel()?>
    		<?php echo $this->element->getElement('firstName')->renderViewHelper()?>
        </div>
        <div>
    		<?php echo $this->element->getElement('lastName')->renderLabel()?>
    		<?php echo $this->element->getElement('lastName')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('ci')->renderLabel()?>
    		<?php echo $this->element->getElement('ci')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('year')->renderLabel()?>
            <?php echo $this->element->getElement('year')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('sex')->renderLabel()?>
            <?php echo $this->element->getElement('sex')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('position')->renderLabel()?>
            <?php echo $this->element->getElement('position')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('rank')->renderLabel()?>
            <?php echo $this->element->getElement('rank')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('area')->renderLabel()?>
            <?php echo $this->element->getElement('area')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('dateOfBirth')->renderLabel()?>
            <?php echo $this->element->getElement('dateOfBirth')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('department')->renderLabel()?>
            <?php echo $this->element->getElement('department')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('address')->renderLabel()?>
            <?php echo $this->element->getElement('address')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('phone')->renderLabel()?>
            <?php echo $this->element->getElement('phone')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('phonemobil')->renderLabel()?>
            <?php echo $this->element->getElement('phonemobil')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('email')->renderLabel()?>
            <?php echo $this->element->getElement('email')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('club')->renderLabel()?>
            <?php echo $this->element->getElement('club')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('yearService')->renderLabel()?>
            <?php echo $this->element->getElement('yearService')->renderViewHelper()?>
        </div>
        <!-- Data on the Region -->
        <div>
            <?php echo $this->element->getElement('mission')->renderLabel()?>
            <?php echo $this->element->getElement('mission')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('region')->renderLabel()?>
            <?php echo $this->element->getElement('region')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('district')->renderLabel()?>
            <?php echo $this->element->getElement('district')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('church')->renderLabel()?>
            <?php echo $this->element->getElement('church')->renderViewHelper()?>
        </div>
        <br>
        <h3><?php echo _('Otros Datos')?></h3>
        <div>
            <?php echo $this->element->getElement('gradeSchool')->renderLabel()?>
            <?php echo $this->element->getElement('gradeSchool')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('bloodGroup')->renderLabel()?>
            <?php echo $this->element->getElement('bloodGroup')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('allergies')->renderLabel()?>
            <?php echo $this->element->getElement('allergies')->renderViewHelper()?>
        </div>
         <div>
            <?php echo $this->element->getElement('disease')->renderLabel()?>
            <?php echo $this->element->getElement('disease')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('treatment')->renderLabel()?>
            <?php echo $this->element->getElement('treatment')->renderViewHelper()?>
        </div>
        <div>
            <?php echo $this->element->getElement('classConqueror')->renderLabel()?>
            <?php echo $this->element->getElement('classConqueror')->renderViewHelper()?>
        </div>
        <?php echo $this->element->getElement('saveButton')->renderViewHelper()?>
    </fieldset>
</form>