<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/jquery-lightbox/js/jquery.lightbox-0.5.min.js","text/javascript");?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/js/lib/jquery-lightbox/css/jquery.lightbox-0.5.css");?>

<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/galleryView/js/jquery.timers-1.2.js","text/javascript");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/galleryView/js/jquery.easing.1.3.js","text/javascript");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/galleryView/js/jquery.galleryview-3.0-dev.js","text/javascript");?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/js/lib/galleryView/css/jquery.galleryview-3.0-dev.css");?>
<div id="page-title">
	<span class="title">Blog de Noticias</span>
	<span class="subtitle">Todas las noticias sobre las Iglesias del Distrito "Nuevo Palmar" lo encontraras aqui.</span>
</div>

<!-- Posts -->
<div id="posts">
    <!-- post -->
    <div class="post">
		<!-- shadow -->
		<div class="thumb-shadow">
			<!-- post-thumb -->
			<ul id="myGallery2">
            <?php foreach ($this->pictures as $picture) {?>
			<li><img data-frame="<?php echo $picture->getSrcCrop() . $picture->getFilenameCrop();?>" src="<?php echo $picture->getSrc() . $picture->getFilename();?>" title="<?php echo $picture->getTitle();?>" data-description="<?php echo $picture->getDescription();?>"/></li>
            <?php }?>
            </ul>
			<!-- ENDS post-thumb -->
		</div>
		<!-- ENDS shadow -->

		<br>
		<h3 dir="ltr" align="center"><span style="color: #000000;">Bienvenidos al Bog de Noticias del Distrito</span></h3>
		<h3 dir="ltr" align="center"><span style="color: #000000;">"Nuevo Palmar"</span></h3>
        <p>&nbsp;</p>
        <h4 dir="ltr"><strong>Introducción</strong></h4>
        <p style="text-align: justify;" dir="ltr">
        Aqui encontraras variedad de noticias actulizadas de las actividades de las Iglesias del Distrito Nuevo Palmar, etc.<br>
        “El asunto del Santuario fue la clave que aclaró el misterio del desengaño de 1844. Reveló todo un sistema de verdades, que formaban un conjunto armo­nioso, y demostraban que la mano de Dios había dirigido el gran movimiento adventista y, al poner de manifiesto la situación y la obra de su pueblo, le indi­caba cuál era su deber de allí en adelante” (CS 476).<br>
        Por esto, nuestro estudio de este trimestre es el Santuario de Dios, tanto el modelo terrenal como el original celestial.</p>
	</div>
	<!-- ENDS post -->
</div>
<!-- ENDS Posts -->

<!-- sidebar -->
<ul id="sidebar">
	<li>
	<h6>Categories</h6>
		<ul>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
		</ul>
	</li>

	<li>
	<h6>Archives</h6>
		<ul>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
		</ul>
	</li>
</ul>

<script type="text/javascript">
	$(function() {
		$('#myGallery2').galleryView({
			transition_speed: 1000,
			transition_interval: 2000,
			easing: 'swing',
			show_panels: true,
			show_panel_nav: true,
			enable_overlays: true,

			panel_width: 590,
			panel_height: 295,
			panel_animation: 'slide',
			panel_scale: 'crop',
			overlay_position: 'bottom',
			pan_images: true,
			pan_style: 'drag',
			pan_smoothness: 15,
			start_frame: 1,
			show_filmstrip: true,
			show_filmstrip_nav: true,
			enable_slideshow: true,
			autoplay: true,
			show_captions: true,
			filmstrip_size: 3,
			filmstrip_style: 'scroll',
			filmstrip_position: 'bottom',
			frame_width: 164,
			frame_height: 80,
			frame_opacity: 0.5,
			frame_scale: 'crop',
			frame_gap: 5,
			show_infobar: true,
			infobar_opacity: 1
		});
	});
</script>