<ul id="sidebar">
	<!-- init sidebar -->
	<li>
		<h6><?php echo _('Who We?')?></h6>
		<ul>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'history', 'controller'=>'Whowe'));?>" title="<?php echo _('Our History')?>"><?php echo _('Our History')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'visionmission', 'controller'=>'Whowe'));?>" title="<?php echo _('Vision Mission')?>"><?php echo _('Vision Mission')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'logo', 'controller'=>'Whowe'));?>" title="<?php echo _('Our Logo')?>"><?php echo _('Our Logo')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'belief', 'controller'=>'Whowe'));?>" title="<?php echo _('Our Belief')?>"><?php echo _('Our Belief')?></a></li>
		</ul>
	</li>
	<!-- ENDS init sidebar -->
</ul>

<div class="moduletable">
    <div class="module-inner">
        <p style="text-align: center;"><img alt="Guillermo Miller" src="/image/guest/leaders/guilherme_miller.jpg" border="0" height="200" width="150"><br>
        Guillermo Miller</p>
        <p style="text-align: center;"><img alt="Santiago White" src="/image/guest/leaders/tiago_white.jpg" border="0" height="200" width="150"><br>
        Santiago White</p>
        <p style="text-align: center;"><img alt="Hellen de White" src="/image/guest/leaders/ellen_white.jpg" border="0" height="200" width="150"><br>
        Ellen de White</p>
        <p style="text-align: center;"><img alt="José Bates" src="/image/guest/leaders/jose_bates.jpg" border="0" height="200" width="150"><br>
        José Bates</p>
        <p style="text-align: center;"><img alt="John Andrews" src="/image/guest/leaders/john_andrews.jpg" border="0" height="200" width="150"><br>
        John Andrews</p>
    </div>
</div>