<ul id="sidebar">
	<li>
	<h6><?php echo _('Categorias')?></h6>
		<ul>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'Index'))?>" title="<?php echo _('Inicio')?>"><?php echo _('Inicio')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'history', 'controller'=>'Whowe'))?>" title="<?php echo _('¿Quienes Somos?')?>"><?php echo _('¿Quienes Somos?')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'News'))?>" title="<?php echo _('Noticias')?>"><?php echo _('Noticias')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'Registration'))?>" title="<?php echo _('Registro')?>"><?php echo _('Registro')?></a></li>
		</ul>
	</li>
</ul>

<div class="moduletable">
    <div class="module-inner">
        <p style="text-align: center;"><img alt="Guillermo Miller" src="/image/guest/leaders/guilherme_miller.jpg" border="0" height="200" width="150"><br>
        Guillermo Miller</p>
        <p style="text-align: center;"><img alt="Santiago White" src="/image/guest/leaders/tiago_white.jpg" border="0" height="200" width="150"><br>
        Santiago White</p>
        <p style="text-align: center;"><img alt="Hellen de White" src="/image/guest/leaders/ellen_white.jpg" border="0" height="200" width="150"><br>
        Ellen de White</p>
        <p style="text-align: center;"><img alt="José Bates" src="/image/guest/leaders/jose_bates.jpg" border="0" height="200" width="150"><br>
        José Bates</p>
        <p style="text-align: center;"><img alt="John Andrews" src="/image/guest/leaders/john_andrews.jpg" border="0" height="200" width="150"><br>
        John Andrews</p>
    </div>
</div>