<ul id="sidebar">
	<!-- init sidebar -->
	<li>
		<h6><?php echo _('Who We?')?></h6>
		<ul>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'history', 'controller'=>'Whowe'));?>" title="<?php echo _('Our History')?>"><?php echo _('Our History')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'visionmission', 'controller'=>'Whowe'));?>" title="<?php echo _('Vision Mission')?>"><?php echo _('Vision Mission')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'logo', 'controller'=>'Whowe'));?>" title="<?php echo _('Our Logo')?>"><?php echo _('Our Logo')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'belief', 'controller'=>'Whowe'));?>" title="<?php echo _('Our Belief')?>"><?php echo _('Our Belief')?></a></li>
		</ul>
	</li>
	<!-- ENDS init sidebar -->
</ul>