<ul id="sidebar">
	<li>
	<h6><?php echo _('Noticias Ministerio Joven')?></h6>
		<ul>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'News'))?>" title="<?php echo _('Aventureros')?>"><?php echo _('Aventureros')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'News'))?>" title="<?php echo _('Conquistadores')?>"><?php echo _('Conquistadores')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'News'))?>" title="<?php echo _('Universitarios')?>"><?php echo _('Universitarios')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'News'))?>" title="<?php echo _('Culto Joven')?>"><?php echo _('Culto Joven')?></a></li>
		</ul>
	</li>

	<li>
	<h6><?php echo _('Categorias')?></h6>
		<ul>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'Index'))?>" title="<?php echo _('Inicio')?>"><?php echo _('Inicio')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'history', 'controller'=>'Whowe'))?>" title="<?php echo _('¿Quienes Somos?')?>"><?php echo _('¿Quienes Somos?')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'News'))?>" title="<?php echo _('Noticias')?>"><?php echo _('Noticias')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'Registration'))?>" title="<?php echo _('Registro')?>"><?php echo _('Registro')?></a></li>
		</ul>
	</li>
</ul>