<ul id="sidebar">
	<!-- init sidebar -->
	<li>
		<h6><?php echo _('Who We?')?></h6>
		<ul>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'history', 'controller'=>'Whowe'));?>" title="<?php echo _('Our History')?>"><?php echo _('Nuestra Historia')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'visionmission', 'controller'=>'Whowe'));?>" title="<?php echo _('Vision Mission')?>"><?php echo _('Vision Mision')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'logo', 'controller'=>'Whowe'));?>" title="<?php echo _('Our Logo')?>"><?php echo _('Nuestros Logos')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'belief', 'controller'=>'Whowe'));?>" title="<?php echo _('Our Belief')?>"><?php echo _('Nuestras Creencias')?></a></li>
		</ul>
	</li>
	<!-- ENDS init sidebar -->
</ul>