<ul id="sidebar">
	<li>
	<h6>Clubes de Conquistadores</h6>
		<ul>
            <li class="cat-item"><a href="<?php echo $this->url(array('action'=>'orion', 'controller'=>'Pathfinder'));?>" title="Club Orion"><?php echo _('Club Orion')?></a></li>
            <li class="cat-item"><a href="<?php echo $this->url(array('action'=>'alasorion', 'controller'=>'Pathfinder'));?>" title="Club Alas de Orion"><?php echo _('Club Alas de Orion')?></a></li>
			<li class="cat-item"><a href="<?php echo $this->url(array('action'=>'nuevooriente', 'controller'=>'Pathfinder'));?>" title="Club Nuevo Oriente"><?php echo _('Club Nuevo Oriente')?></a></li>
		</ul>
	</li>

	<li>
	<h6>Aventureros</h6>
		<ul>
			<li class="cat-item"><a href="#" title="View all posts">Imagenes</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
			<li class="cat-item"><a href="#" title="View all posts">Pellentesque habitant morbi</a></li>
		</ul>
	</li>
</ul>