INSERT INTO `tblMission` ( `name`, `abreviation`, `description`, `created`, `changed`, `createdBy`, `changedBy`, `state`) VALUES
( 'Mision Boliviana Occidental', 'MBO', 'Zona Occidental de Bolivia', NOW(), NULL, 1, NULL, 1),
( 'Mision Bolivia Central', 'MBC', 'Zona Central de Bolivia', NOW(), NULL, 1, NULL, 1),
( 'Mision del Oriente Boliviano', 'MOB', 'Zona Oriental de Bolivia', NOW(), NULL, 1, NULL, 1);

INSERT INTO `tblRegion` ( `name`, `abreviation`, `description`, `missionId`, `created`, `changed`, `createdBy`, `changedBy`, `state`) VALUES
( 'Region - A', 'A', '', 3, NOW(), NULL, 1, NULL, 1),
( 'Region - B', 'B', '', 3, NOW(), NULL, 1, NULL, 1),
( 'Region - C', 'C', '', 3, NOW(), NULL, 1, NULL, 1),
( 'Region - D', 'D', '', 3, NOW(), NULL, 1, NULL, 1),
( 'Region - E', 'E', '', 3, NOW(), NULL, 1, NULL, 1),
( 'Region - F', 'F', '', 3, NOW(), NULL, 1, NULL, 1),
( 'Region - G', 'G', '', 3, NOW(), NULL, 1, NULL, 1),
( 'Region - H', 'H', '', 3, NOW(), NULL, 1, NULL, 1),
( 'Region - I', 'I', '', 3, NOW(), NULL, 1, NULL, 1),
( 'Region - J', 'J', '', 3, NOW(), NULL, 1, NULL, 1),
( 'Region - K', 'K', '', 3, NOW(), NULL, 1, NULL, 1);

INSERT INTO `tblDistrict` ( `name`, `description`, `regionId`, `created`, `changed`, `createdBy`, `changedBy`, `state`) VALUES
( 'S.C. Central', '', 1, NOW(), NULL, 1, NULL, 1),
( 'S.C. Hamacas', '', 1, NOW(), NULL, 1, NULL, 1),
( 'S.C. Barrio Lindo', '', 1, NOW(), NULL, 1, NULL, 1),

( 'S.C. Villa 1 de Mayo', '', 2, NOW(), NULL, 1, NULL, 1),
( 'S.C. Plan 3000', '', 2, NOW(), NULL, 1, NULL, 1),
( 'S.C. Arroyito', '', 2, NOW(), NULL, 1, NULL, 1),
( 'S.C. Paurito', '', 2, NOW(), NULL, 1, NULL, 1),

( 'S.C. La Colorada', '', 3, NOW(), NULL, 1, NULL, 1),
( 'S.C. Nuevo Palmar', '', 3, NOW(), NULL, 1, NULL, 1),
( 'S.C. Sur', '', 3, NOW(), NULL, 1, NULL, 1),

( 'S.C. Pari', '', 4, NOW(), NULL, 1, NULL, 1),
( 'S.C. Suroeste', '', 4, NOW(), NULL, 1, NULL, 1),
( 'S.C. Pirai', '', 4, NOW(), NULL, 1, NULL, 1),
( 'S.C. Samaipata', '', 4, NOW(), NULL, 1, NULL, 1),

( 'S.C. Norte', '', 5, NOW(), NULL, 1, NULL, 1),
( 'S.C. Noreste', '', 5, NOW(), NULL, 1, NULL, 1),
( 'S.C. Soberania', '', 5, NOW(), NULL, 1, NULL, 1),

( 'Montero Central', '', 6, NOW(), NULL, 1, NULL, 1),
( 'Montero Norte', '', 6, NOW(), NULL, 1, NULL, 1),
( 'Warnes', '', 6, NOW(), NULL, 1, NULL, 1),
( 'Yapacani', '', 6, NOW(), NULL, 1, NULL, 1),

( 'Chiquitania - A', '', 7, NOW(), NULL, 1, NULL, 1),
( 'Chiquitania - B', '', 7, NOW(), NULL, 1, NULL, 1),
( 'Puerto Suarez', '', 7, NOW(), NULL, 1, NULL, 1),

( 'Yacuiba - A', '', 8, NOW(), NULL, 1, NULL, 1),
( 'Yacuiba - B', '', 8, NOW(), NULL, 1, NULL, 1),
( 'Villamontes', '', 8, NOW(), NULL, 1, NULL, 1),

( 'Tarija Central', '', 9, NOW(), NULL, 1, NULL, 1),
( 'Tarija Loma Linda', '', 9, NOW(), NULL, 1, NULL, 1),
( 'Bermejo', '', 9, NOW(), NULL, 1, NULL, 1),

( 'Trinidad Central', '', 10, NOW(), NULL, 1, NULL, 1),
( 'Trinidad Sureste', '', 10, NOW(), NULL, 1, NULL, 1),
( 'Trinidad Suroeste', '', 10, NOW(), NULL, 1, NULL, 1),
( 'Mamore', '', 10, NOW(), NULL, 1, NULL, 1),

( 'Riberalta', '', 11, NOW(), NULL, 1, NULL, 1),
( 'Guayaramerin', '', 11, NOW(), NULL, 1, NULL, 1);


INSERT INTO `tblChurch` ( `name`, `description`, `districtId`, `created`, `changed`, `createdBy`, `changedBy`, `state`) VALUES
-- Central
( 'Central A', '', 1, NOW(), NULL, 1, NULL, 1),
( 'Central B', '', 1, NOW(), NULL, 1, NULL, 1),
( 'Guardia Nueva', '', 1, NOW(), NULL, 1, NULL, 1),
( 'Maranatha - Guardia Nueva', '', 1, NOW(), NULL, 1, NULL, 1),
( 'Mensajeros de Dios', '', 1, NOW(), NULL, 1, NULL, 1),
-- Hamacas
( 'Hamacas', '', 2, NOW(), NULL, 1, NULL, 1),
( 'San Juan', '', 2, NOW(), NULL, 1, NULL, 1),
( 'Barrio Oriental', '', 2, NOW(), NULL, 1, NULL, 1),
-- Barrio Lindo
( 'Barrio Lindo', '', 3, NOW(), NULL, 1, NULL, 1),
( 'Barrio Militar', '', 3, NOW(), NULL, 1, NULL, 1),
( 'Heroes del Chaco', '', 3, NOW(), NULL, 1, NULL, 1),
( 'Oriente', '', 3, NOW(), NULL, 1, NULL, 1),
-- Villa 1 de Mayo
( '15 de Abril', '', 4, NOW(), NULL, 1, NULL, 1),
( '30 de Enero', '', 4, NOW(), NULL, 1, NULL, 1),
( 'Villa 1ro de Mayo', '', 4, NOW(), NULL, 1, NULL, 1),
( 'Villa Alegre', '', 4, NOW(), NULL, 1, NULL, 1),
( 'Villa Cochabamba', '', 4, NOW(), NULL, 1, NULL, 1),
( 'Union Campeche', '', 4, NOW(), NULL, 1, NULL, 1),
( '4 de Febrero', '', 4, NOW(), NULL, 1, NULL, 1),
-- Plan 3000
( 'Plan 3000', '', 5, NOW(), NULL, 1, NULL, 1),
( '2 de Abril', '', 5, NOW(), NULL, 1, NULL, 1),
-- Arroyito
( 'Primavera', '', 6, NOW(), NULL, 1, NULL, 1),
( 'Barrio Nuevo', '', 6, NOW(), NULL, 1, NULL, 1),
( 'Emanuel - A', '', 6, NOW(), NULL, 1, NULL, 1),
( 'Gedeon', '', 6, NOW(), NULL, 1, NULL, 1),
( 'Internacional', '', 6, NOW(), NULL, 1, NULL, 1),
( 'Pepe Lucho', '', 6, NOW(), NULL, 1, NULL, 1),
( '7 de Julio', '', 6, NOW(), NULL, 1, NULL, 1),
-- Paurito
( 'El Quior', '', 7, NOW(), NULL, 1, NULL, 1),
( 'El Recreo', '', 7, NOW(), NULL, 1, NULL, 1),
( 'La Esperanza es Jesus', '', 7, NOW(), NULL, 1, NULL, 1),
( 'Maranatha Paurito', '', 7, NOW(), NULL, 1, NULL, 1),
( 'Nazaret', '', 7, NOW(), NULL, 1, NULL, 1),
( 'Nuevo Mundo', '', 7, NOW(), NULL, 1, NULL, 1),
( 'Paurito', '', 7, NOW(), NULL, 1, NULL, 1),
( 'Pueblo Nuevo', '', 7, NOW(), NULL, 1, NULL, 1),
( 'Santa Carla', '', 7, NOW(), NULL, 1, NULL, 1),
( 'Villa Paraiso', '', 7, NOW(), NULL, 1, NULL, 1),
( 'La Campinia', '', 7, NOW(), NULL, 1, NULL, 1),
-- La Colorada
( 'Amboro', '', 8, NOW(), NULL, 1, NULL, 1),
( 'Cristo Rey', '', 8, NOW(), NULL, 1, NULL, 1),
( 'El Fuerte', '', 8, NOW(), NULL, 1, NULL, 1),
( 'La Colorada', '', 8, NOW(), NULL, 1, NULL, 1),
( 'Roca y Coronado', '', 8, NOW(), NULL, 1, NULL, 1),
( 'Sausalito de Jordan', '', 8, NOW(), NULL, 1, NULL, 1),
-- Nuevo Palmar
( 'Islas del Palmar', '', 9, NOW(), NULL, 1, NULL, 1),
( 'Nuevo Oriente', '', 9, NOW(), NULL, 1, NULL, 1),
( 'Nuevo Palmar', '', 9, NOW(), NULL, 1, NULL, 1),
( 'Palmira Plan 4000', '', 9, NOW(), NULL, 1, NULL, 1),
( 'Roca Eterna', '', 9, NOW(), NULL, 1, NULL, 1),
-- Sur
( 'Dulce Hogar', '', 10, NOW(), NULL, 1, NULL, 1),
( 'Heraldos de la Fe', '', 10, NOW(), NULL, 1, NULL, 1),
( 'Heroes de la Fe', '', 10, NOW(), NULL, 1, NULL, 1),
( 'Huestes de la Fe', '', 10, NOW(), NULL, 1, NULL, 1),
( 'Las Americas', '', 10, NOW(), NULL, 1, NULL, 1),
( 'Tierras Nuevas', '', 10, NOW(), NULL, 1, NULL, 1),
( 'Vinia del Senior', '', 10, NOW(), NULL, 1, NULL, 1),
-- Pari
( '4 de Noviembre', '', 11, NOW(), NULL, 1, NULL, 1),
( 'El Pari', '', 11, NOW(), NULL, 1, NULL, 1),
( 'Kilometro 13', '', 11, NOW(), NULL, 1, NULL, 1),
( 'Kilometro 14', '', 11, NOW(), NULL, 1, NULL, 1),
( 'La Colina C', '', 11, NOW(), NULL, 1, NULL, 1),
( 'Radial 17 medio', '', 11, NOW(), NULL, 1, NULL, 1),
( 'Villa Fatima', '', 11, NOW(), NULL, 1, NULL, 1),
( 'Villa Rosario', '', 11, NOW(), NULL, 1, NULL, 1),
-- SurOeste
( 'Bajo Beni', '', 12, NOW(), NULL, 1, NULL, 1),
( 'Balcon II', '', 12, NOW(), NULL, 1, NULL, 1),
( 'Canaan', '', 12, NOW(), NULL, 1, NULL, 1),
( 'Canto de Esperanza', '', 12, NOW(), NULL, 1, NULL, 1),
( 'Carmen Mapaizo', '', 12, NOW(), NULL, 1, NULL, 1),
( 'Kilometro 6', '', 12, NOW(), NULL, 1, NULL, 1),
( 'Mora', '', 12, NOW(), NULL, 1, NULL, 1),
( 'Pedro Lorenzo', '', 12, NOW(), NULL, 1, NULL, 1),
( 'Tentami', '', 12, NOW(), NULL, 1, NULL, 1),
( 'Los Piyos', '', 12, NOW(), NULL, 1, NULL, 1),
-- Pirai
( 'Angostura', '', 13, NOW(), NULL, 1, NULL, 1),
( 'El Torno', '', 13, NOW(), NULL, 1, NULL, 1),
( 'Jorochito', '', 13, NOW(), NULL, 1, NULL, 1),
( 'Limoncito', '', 13, NOW(), NULL, 1, NULL, 1),
( 'Pampa', '', 13, NOW(), NULL, 1, NULL, 1),
( 'Puerto Rico', '', 13, NOW(), NULL, 1, NULL, 1),
( 'San Jose - Pirai', '', 13, NOW(), NULL, 1, NULL, 1),
( 'San Luis', '', 13, NOW(), NULL, 1, NULL, 1),
( 'Taruma', '', 13, NOW(), NULL, 1, NULL, 1),

-- Samaipata
( 'Lajas', '', 14, NOW(), NULL, 1, NULL, 1),
( 'Mairana', '', 14, NOW(), NULL, 1, NULL, 1),
( 'Palermo', '', 14, NOW(), NULL, 1, NULL, 1),
( 'Saipina', '', 14, NOW(), NULL, 1, NULL, 1),
( 'Samaipata', '', 14, NOW(), NULL, 1, NULL, 1),
( 'Vallegrande', '', 14, NOW(), NULL, 1, NULL, 1),
-- Norte
( 'Abaroa', '', 15, NOW(), NULL, 1, NULL, 1),
( 'CASC', '', 15, NOW(), NULL, 1, NULL, 1),
( 'Kilometro 5', '', 15, NOW(), NULL, 1, NULL, 1),
( 'Melchor Pinto', '', 15, NOW(), NULL, 1, NULL, 1),
( 'San Joaquin', '', 15, NOW(), NULL, 1, NULL, 1),
( 'Sausalito', '', 15, NOW(), NULL, 1, NULL, 1),
( 'Tusequis', '', 15, NOW(), NULL, 1, NULL, 1),
( 'Universitaria km5', '', 15, NOW(), NULL, 1, NULL, 1),
-- Noreste
( 'Cotoca', '', 16, NOW(), NULL, 1, NULL, 1),
( 'Dorado Norte', '', 16, NOW(), NULL, 1, NULL, 1),
( 'Libertad', '', 16, NOW(), NULL, 1, NULL, 1),
( 'Los Chacos', '', 16, NOW(), NULL, 1, NULL, 1),
( 'Los Claveles', '', 16, NOW(), NULL, 1, NULL, 1),
( 'Pailon', '', 16, NOW(), NULL, 1, NULL, 1),
( 'Toborochi', '', 16, NOW(), NULL, 1, NULL, 1),
( '25 de Mayo', '', 16, NOW(), NULL, 1, NULL, 1),
( '26 de Septiembre', '', 16, NOW(), NULL, 1, NULL, 1),
( 'Don Lorenzo', '', 16, NOW(), NULL, 1, NULL, 1),
-- Soberania
( 'Cielito Lindo', '', 17, NOW(), NULL, 1, NULL, 1),
( 'El Buen Samaritano', '', 17, NOW(), NULL, 1, NULL, 1),
( 'Los Andes', '', 17, NOW(), NULL, 1, NULL, 1),
( 'Pampa de la Isla', '', 17, NOW(), NULL, 1, NULL, 1),
( 'Retonio', '', 17, NOW(), NULL, 1, NULL, 1),
( 'San Juan', '', 17, NOW(), NULL, 1, NULL, 1),
( 'Soberania', '', 17, NOW(), NULL, 1, NULL, 1),
-- Montero Central
( 'Floresta', '', 18, NOW(), NULL, 1, NULL, 1),
( 'La Pampa', '', 18, NOW(), NULL, 1, NULL, 1),
( 'Montero Central', '', 18, NOW(), NULL, 1, NULL, 1),
( 'Portachuelo', '', 18, NOW(), NULL, 1, NULL, 1),
( 'Villa Virginia', '', 18, NOW(), NULL, 1, NULL, 1),
-- Montero Norte
( '2 de Agosto', '', 19, NOW(), NULL, 1, NULL, 1),
( 'Minero A', '', 19, NOW(), NULL, 1, NULL, 1),
( 'Mienro B', '', 19, NOW(), NULL, 1, NULL, 1),
( 'Porfia', '', 19, NOW(), NULL, 1, NULL, 1),
( 'Puesto Fernandes', '', 19, NOW(), NULL, 1, NULL, 1),
( 'Rodeo del Norte', '', 19, NOW(), NULL, 1, NULL, 1),
( 'San Jose', '', 19, NOW(), NULL, 1, NULL, 1),
( 'San Jose del Norte', '', 19, NOW(), NULL, 1, NULL, 1),
( 'San Pedro', '', 19, NOW(), NULL, 1, NULL, 1),
( 'Villa Rosario', '', 19, NOW(), NULL, 1, NULL, 1),
( '27 de Agosto', '', 19, NOW(), NULL, 1, NULL, 1),
( 'Chane Bedoya', '', 19, NOW(), NULL, 1, NULL, 1),
( 'Chane Independiente', '', 19, NOW(), NULL, 1, NULL, 1),
( 'Los Troncos', '', 19, NOW(), NULL, 1, NULL, 1),
-- Warnez
( 'Ebenezer', '', 20, NOW(), NULL, 1, NULL, 1),
( 'Gran Paititi', '', 20, NOW(), NULL, 1, NULL, 1),
( 'Juan Pablo II', '', 20, NOW(), NULL, 1, NULL, 1),
( 'Pentaguasu I', '', 20, NOW(), NULL, 1, NULL, 1),
( 'Satelite Norte', '', 20, NOW(), NULL, 1, NULL, 1),
( 'Warnez', '', 20, NOW(), NULL, 1, NULL, 1),
-- Yapacani
( 'Agua Dulce', '', 21, NOW(), NULL, 1, NULL, 1),
( 'Alianza Norte', '', 21, NOW(), NULL, 1, NULL, 1),
( 'El Chore', '', 21, NOW(), NULL, 1, NULL, 1),
( 'Nueva Belen', '', 21, NOW(), NULL, 1, NULL, 1),
( 'Nueva Jerusalen', '', 21, NOW(), NULL, 1, NULL, 1),
( 'San Juan', '', 21, NOW(), NULL, 1, NULL, 1),
( 'Santa Fe', '', 21, NOW(), NULL, 1, NULL, 1),
( 'Yapacani', '', 21, NOW(), NULL, 1, NULL, 1),
( 'Surutu', '', 21, NOW(), NULL, 1, NULL, 1),
-- Chiquitania - A
( 'Alemanes', '', 22, NOW(), NULL, 1, NULL, 1),
( 'Asencion de Guarayos', '', 22, NOW(), NULL, 1, NULL, 1),
( 'Berlin', '', 22, NOW(), NULL, 1, NULL, 1),
( 'Brecha Cas. N-23', '', 22, NOW(), NULL, 1, NULL, 1),
( 'Brecha Cas. N-47', '', 22, NOW(), NULL, 1, NULL, 1),
( 'Brecha Cas. N-50', '', 22, NOW(), NULL, 1, NULL, 1),
( 'Cuatro Caniadas', '', 22, NOW(), NULL, 1, NULL, 1),
( 'San Ramon', '', 22, NOW(), NULL, 1, NULL, 1),
( 'El Puente', '', 22, NOW(), NULL, 1, NULL, 1),
( 'San Julian', '', 22, NOW(), NULL, 1, NULL, 1),
-- Chiquitania - B
( 'Concepcion', '', 23, NOW(), NULL, 1, NULL, 1),
( 'Emanuel', '', 23, NOW(), NULL, 1, NULL, 1),
( 'La Curicha', '', 23, NOW(), NULL, 1, NULL, 1),
( 'San Matias', '', 23, NOW(), NULL, 1, NULL, 1),
( 'San Ignacio', '', 23, NOW(), NULL, 1, NULL, 1),
( 'San Miguel', '', 23, NOW(), NULL, 1, NULL, 1),
-- Puerto Suarez
( 'Bocaina', '', 24, NOW(), NULL, 1, NULL, 1),
( 'El Carmen', '', 24, NOW(), NULL, 1, NULL, 1),
( 'Puerto Quijarro', '', 24, NOW(), NULL, 1, NULL, 1),
( 'Puerto Suarez', '', 24, NOW(), NULL, 1, NULL, 1),
( 'Robore', '', 24, NOW(), NULL, 1, NULL, 1),
( 'San Salvador', '', 24, NOW(), NULL, 1, NULL, 1),
-- Yacuiba - A
( 'Caiza', '', 25, NOW(), NULL, 1, NULL, 1),
( 'El Palmar Chico', '', 25, NOW(), NULL, 1, NULL, 1),
( 'Grampa', '', 25, NOW(), NULL, 1, NULL, 1),
( 'Porvenir', '', 25, NOW(), NULL, 1, NULL, 1),
( 'Yacuiba', '', 25, NOW(), NULL, 1, NULL, 1),
( 'Yaguacua', '', 25, NOW(), NULL, 1, NULL, 1),
-- Yacuiba - B
( 'Barrio Nuevo', '', 26, NOW(), NULL, 1, NULL, 1),
( 'Barrio Obrero', '', 26, NOW(), NULL, 1, NULL, 1),
( 'Carapari', '', 26, NOW(), NULL, 1, NULL, 1),
( 'El Prado', '', 26, NOW(), NULL, 1, NULL, 1),
( 'San Juan', '', 26, NOW(), NULL, 1, NULL, 1),
( 'Laime', '', 26, NOW(), NULL, 1, NULL, 1),
-- Villamontes
( 'Arenales', '', 27, NOW(), NULL, 1, NULL, 1),
( 'Bilbao', '', 27, NOW(), NULL, 1, NULL, 1),
( 'Camiri', '', 27, NOW(), NULL, 1, NULL, 1),
( 'Ferroviaria', '', 27, NOW(), NULL, 1, NULL, 1),
( 'Machareti', '', 27, NOW(), NULL, 1, NULL, 1),
( 'Monteagudo', '', 27, NOW(), NULL, 1, NULL, 1),
( 'Villamontes', '', 27, NOW(), NULL, 1, NULL, 1),
-- Tarija Central
( 'Advenir', '', 28, NOW(), NULL, 1, NULL, 1),
( 'Chiquiaca', '', 28, NOW(), NULL, 1, NULL, 1),
( 'Futuro con Esperanza', '', 28, NOW(), NULL, 1, NULL, 1),
( 'Las Palmas', '', 28, NOW(), NULL, 1, NULL, 1),
( 'Nueva Esperanza', '', 28, NOW(), NULL, 1, NULL, 1),
( 'Pampa de la Esperanza', '', 28, NOW(), NULL, 1, NULL, 1),
( 'Tarija', '', 28, NOW(), NULL, 1, NULL, 1),
( 'El Palmar', '', 28, NOW(), NULL, 1, NULL, 1),
( 'Monte Mayor', '', 28, NOW(), NULL, 1, NULL, 1),
( 'Orocote', '', 28, NOW(), NULL, 1, NULL, 1),
( 'Renacer', '', 28, NOW(), NULL, 1, NULL, 1),
-- Tarija Loma Linda
( 'El Paraiso', '', 29, NOW(), NULL, 1, NULL, 1),
( 'La Florida', '', 29, NOW(), NULL, 1, NULL, 1),
( 'La Gran Esperanza', '', 29, NOW(), NULL, 1, NULL, 1),
( 'Loma Linda', '', 29, NOW(), NULL, 1, NULL, 1),
( 'Nueva Luz', '', 29, NOW(), NULL, 1, NULL, 1),
( 'Maranata - Tarija', '', 29, NOW(), NULL, 1, NULL, 1),
( 'Nuevo Eden', '', 29, NOW(), NULL, 1, NULL, 1),
-- Bermejo Tarija
( 'Bermejo', '', 30, NOW(), NULL, 1, NULL, 1),
( 'La Nueva Esperanza', '', 30, NOW(), NULL, 1, NULL, 1),
( 'Nueva Jerusalen', '', 30, NOW(), NULL, 1, NULL, 1),
-- Trinidad Central cambiar por Trinida Norte
( 'Trinidad Central', '', 31, NOW(), NULL, 1, NULL, 1),
( 'Nueva Trinidad', '', 31, NOW(), NULL, 1, NULL, 1),
( 'Fortaleza', '', 31, NOW(), NULL, 1, NULL, 1),
( 'Paititi', '', 31, NOW(), NULL, 1, NULL, 1),
-- Trinidad Sur Este
( 'Fatima', '', 32, NOW(), NULL, 1, NULL, 1),
( 'Pompeya', '', 32, NOW(), NULL, 1, NULL, 1),
( 'Puente San Pablo', '', 32, NOW(), NULL, 1, NULL, 1),
( 'Nueva Jerusalen', '', 32, NOW(), NULL, 1, NULL, 1),
( 'La Vid', '', 32, NOW(), NULL, 1, NULL, 1),
( 'La Esperanza', '', 32, NOW(), NULL, 1, NULL, 1),
-- Trinidad Sur Oeste
( 'CAT', '', 33, NOW(), NULL, 1, NULL, 1),
( 'Retonio', '', 33, NOW(), NULL, 1, NULL, 1),
( 'Mangalito', '', 33, NOW(), NULL, 1, NULL, 1),
( 'Maranatha', '', 33, NOW(), NULL, 1, NULL, 1),
( 'San Ignacio de Moxos', '', 33, NOW(), NULL, 1, NULL, 1),
( 'El Retonio Trinidad', '', 33, NOW(), NULL, 1, NULL, 1),
-- Mamore
( 'No Existen Datos', '', 34, NOW(), NULL, 1, NULL, 1),
-- Riberalta
( '1 de Diciembre', '', 35, NOW(), NULL, 1, NULL, 1),
( '7 de Agosto', '', 35, NOW(), NULL, 1, NULL, 1),
( 'Centenario Petrolero', '', 35, NOW(), NULL, 1, NULL, 1),
( 'Conavi', '', 35, NOW(), NULL, 1, NULL, 1),
( 'Integracion', '', 35, NOW(), NULL, 1, NULL, 1),
( 'Litoral - Riberalta', '', 35, NOW(), NULL, 1, NULL, 1),
( 'Los Tajibos', '', 35, NOW(), NULL, 1, NULL, 1),
( 'Pueblo Nuevo R', '', 35, NOW(), NULL, 1, NULL, 1),
( 'Riberalta Central', '', 35, NOW(), NULL, 1, NULL, 1),
( 'Villa Britanica Central', '', 35, NOW(), NULL, 1, NULL, 1),
-- Guayaramerin
( '8 de Diciembre', '', 36, NOW(), NULL, 1, NULL, 1),
( 'Filadelfia', '', 36, NOW(), NULL, 1, NULL, 1),
( 'Guayara Central', '', 36, NOW(), NULL, 1, NULL, 1),
( 'Guayaraguazu', '', 36, NOW(), NULL, 1, NULL, 1),
( 'Los Almedros', '', 36, NOW(), NULL, 1, NULL, 1),
( 'Pueblo Nuevo', '', 36, NOW(), NULL, 1, NULL, 1)
;