<?php

namespace Model\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * ChurchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChurchRepository extends EntityRepository {

    /**
     *
     * Returns the names of the models
     * @return array
     */
    public function findAllName() {
        $connection = $this->_em->getConnection();
        $churches = $connection->fetchAll('SELECT id, name FROM tblChurch');

        $data = array();
        foreach ($churches as $row) {
            $data[$row['id']] = $row['name'];
        }

        return $data;
    }
}