<?php

namespace Model\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * ClubPathfinderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubPathfinderRepository extends EntityRepository {

    /**
	 * Alias of the table
	 * @var string
	 */
	private $_alias = 'pathfinder';

	/**
	 * Returns models according the filters
	 * @param array $filters
	 * @param int $limit
	 * @param int $offset
	 * @param int $sortColumn
	 * @param string $sortDirection
	 * @return Array Objects
	 */
	public function findByCriteria($filters = array(), $limit = NULL, $offset = NULL, $sortColumn = NULL, $sortDirection = NULL) {
		$query = $this->_em->createQueryBuilder();

		$condName = "";
		foreach ($filters as $filter) {
			$condName = "$this->_alias.name LIKE :name AND ";
			$query->setParameter($filter['field'], $filter['filter']);
		}

		$query->select($this->_alias)
				->from($this->_entityName, $this->_alias)
				->where("$condName $this->_alias.state = TRUE")
				->setFirstResult($offset)
				->setMaxResults($limit);

		$sort = '';
		switch ($sortColumn) {
			case 1:
				$sort = 'name';
				break;

			case 2:
				$sort = 'textbible';
				break;

			case 3:
				$sort = 'textbible';
				break;

			case 4:
				$sort = 'created';
				break;

			case 5:
				$sort = 'changed';
				break;

			default: $sort = 'id'; $sortDirection = 'desc';
		}

		$query->orderBy("$this->_alias.$sort", $sortDirection);

		return $query->getQuery()->getResult();
	}

	/**
	 * Finds count of models according the filters
	 * @param array $filters
	 * @return int
	 */
	public function getTotalCount($filters = array()) {
		$query = $this->_em->createQueryBuilder();

		$condName = "";
		foreach ($filters as $filter) {
			$condName = "$this->_alias.name LIKE :name AND ";
			$query->setParameter($filter['field'], $filter['filter']);
		}

		$query->select("count($this->_alias.id)")
				->from($this->_entityName, $this->_alias)
				->where("$condName $this->_alias.state = TRUE");

		return (int)$query->getQuery()->getSingleScalarResult();
	}

	/**
	 * (non-PHPdoc)
	 * @see Doctrine\ORM.EntityRepository::findAll()
	 */
	public function findAll() {
		return $this->findBy(array('state' => 1));
	}

	/**
	 * Verifies if the name Club pathfinder already exist it.
	 * @param string $name
	 * @return boolean
	 */
	public function verifyExistName($name) {
		$object = $this->findOneBy(array('name' => $name, 'state' => TRUE));
		return $object != NULL? TRUE : FALSE;
	}

	/**
	 *
	 * Verifies if the id and name Club pathfinder already exist it.
	 * @param int $id
	 * @param string $name
	 */
	public function verifyExistIdAndName($id, $name) {
		$object = $this->findOneBy(array('id' => $id, 'name' => $name, 'state' => TRUE));
		return $object != NULL? TRUE : FALSE;
	}

	/**
	 * (non-PHPdoc)
	 * @see Doctrine\ORM.EntityRepository::find()
	 */
	public function find($id) {
		return $this->findOneBy(array('id' => $id, 'state' => TRUE));
	}

	/**
	 * Returns all club pathfinders
	 * @return array
	 */
	public function findAllArray() {
		$clubs = $this->findAll();

		$clubPathfinderArray = array();
		foreach ($clubs as $club) {
			$clubPathfinderArray[$club->getId()] = $club->getName();
		}

		return $clubPathfinderArray;
	}
}