<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/blueimp-Load-Image/load-image.min.js","text/javascript"); ?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/Directive.js","text/javascript");?>

<!-- title -->
<div id="page-title">
    <span class="title"><?php echo _('Registro del Club de Conquistadores')?></span>
	<span class="subtitle"><?php echo _('Ficha de Registro del Club de Conquistadores')?></span>
</div>
<!-- ENDS title -->

<!-- Posts -->
<div id="posts">
	<!-- post -->
	<div class="post">
		<div class="thumb-shadow">
		<!-- form -->
		<?php echo $this->form;?>
		</div>
	</div>
	<!-- ENDS post -->
</div>
<!-- ENDS Posts -->

<script type="text/javascript">
$(document).ready(function() {
	var result = $('#result'),
		load = function (e) {
		e = e.originalEvent;
		e.preventDefault();
		window.loadImage(
			(e.dataTransfer || e.target).files[0],
			function (img) {
				result.children().replaceWith(img);
			},
			{
			maxWidth: result.children().outerWidth(),
			canvas: true
			}
		);
	};

	$('#file-input').change(load);


	$('#saveButton').click(function() {
		   $('#formId').submit();
		    });
});

$("#mission").change(function () {
	this.missionId = $("#mission").val();

	// Sends request by ajax
	$.ajax({
	url: '<?php echo $this->url(array('controller'=>'Registration', 'action'=>'ds-region'));?>',
	type: "POST",
	dataType: 'json',
	data: {'missionId' : this.missionId },
	beforeSend: function(XMLHttpRequest) {
		return true;
	},

	success: function(data, textStatus, XMLHttpRequest) {
		// Removes all options for the select box
		$('#region option').remove();
		// .each loops through the array
		$.each(data.regionsArray, function(i) {
			$('#region').append($("<option></option>")
				.attr("value", i)
				.text(data.regionsArray[i]));
		});
	},

	complete: function(jqXHR, textStatus) {},

	error: function(jqXHR, textStatus, errorThrown) {}
    });
});

$("#region").change(function () {
	this.regionId = $("#region").val();

	// Sends request by ajax
	$.ajax({
	url: '<?php echo $this->url(array('controller'=>'Registration', 'action'=>'ds-district'));?>',
	type: "POST",
	dataType: 'json',
	data: {'regionId' : this.regionId },
	beforeSend: function(XMLHttpRequest) {
		return true;
	},

	success: function(data, textStatus, XMLHttpRequest) {
		// Removes all options for the select box
		$('#district option').remove();
		// .each loops through the array
		$.each(data.districtsArray, function(i) {
			$('#district').append($("<option></option>")
				.attr("value", i)
				.text(data.districtsArray[i]));
		});
	},

	complete: function(jqXHR, textStatus) {},

	error: function(jqXHR, textStatus, errorThrown) {}
    });
});

$("#district").change(function () {
	this.districtId = $("#district").val();

	// Sends request by ajax
	$.ajax({
	url: '<?php echo $this->url(array('controller'=>'Registration', 'action'=>'ds-church'));?>',
	type: "POST",
	dataType: 'json',
	data: {'districtId' : this.districtId },
	beforeSend: function(XMLHttpRequest) {
		return true;
	},

	success: function(data, textStatus, XMLHttpRequest) {
		// Removes all options for the select box
		$('#church option').remove();
		// .each loops through the array
		$.each(data.churchesArray, function(i) {
			$('#church').append($("<option></option>")
				.attr("value", i)
				.text(data.churchesArray[i]));
		});
	},

	complete: function(jqXHR, textStatus) {},

	error: function(jqXHR, textStatus, errorThrown) {}
    });
});

$('#church').change(function () {
	this.churchId = $('#church').val();

	// Sends request by ajax
	$.ajax({
	url: '<?php echo $this->url(array('controller'=>'Registration', 'action'=>'ds-club'));?>',
	type: "POST",
	dataType: 'json',
	data: {'churchId' : this.churchId },
	beforeSend: function(XMLHttpRequest) {
		return true;
	},

	success: function(data, textStatus, XMLHttpRequest) {
		// Removes all options for the select box
		$('#club option').remove();
		// .each loops through the array
		$.each(data.clubesArray, function(i) {
			$('#club').append($("<option></option>")
				.attr("value", i)
				.text(data.clubesArray[i]));
		});
	},

	complete: function(jqXHR, textStatus) {},

	error: function(jqXHR, textStatus, errorThrown) {}
    });
});
</script>