<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/jquery-lightbox/js/jquery.lightbox-0.5.min.js","text/javascript");?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/js/lib/jquery-lightbox/css/jquery.lightbox-0.5.css");?>

<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/jcarousel/jquery.jcarousel.min.js","text/javascript");?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/js/lib/jcarousel/skins/tango/skin.css");?>

<div id="page-title">
	<span class="title">Nuestras historia</span>
	<span class="subtitle">La Iglesia adventista del septimo dia y su historia</span>
</div>

<!-- Posts -->
<div id="posts">
    <!-- post -->
    <div class="post">

<p align="justify">En apenas un siglo y medio la Iglesia Adventista
del Séptimo Día ha crecido de un puñado de personas, que diligentemente
estudiaron la Biblia en búsqueda de la verdad, para una comunidad
mundial de mas de ocho millones de miembros y, otros millones, que
consideran la Iglesia Adventista su hogar espiritual. <br><br>Doctrinariamente,
 los Adventistas del Séptimo Día son herederos del supradenominacional
movimiento Milleriano de la década de 1840. Aunque el nombre “Adventista
 del Séptimo Día” haya sido escogido en 1860, la denominación no fue
oficialmente organizada hasta el 21 de mayo de 1863, cuando el
movimiento incluía cerca de 125 Iglesias y 3.500 miembros. <br><br>Entre
 1831 y 1844, Guillermo (William) Miller - un predicador Bautista y
ex-capitán de Ejército de la Guerra de 1812 - lanzo el grande despertar
del segundo advenimiento, el cual eventualmente se dispersó a través de
la mayoría del mundo cristiano. Basado en su estudio de la profecía de
Daniel 8:14, Miller calculo que Jesús podría retornar a Tierra el 22 de
octubre de 1844. Cuando Jesús no apareció los seguidores de Miller
experimentaron lo que se vino a llamar “El Gran Chasco”. <br><br>La
mayoría de los millares que se habían juntado al movimiento, salio en
profunda desilusión. Unos pocos no en tanto, regresaron para sus Bíblias
 para descubrir porque ellos fueron decepcionados. Luego ellos
concluyeron que la fecha del 22 de octubre era correcta, pero que Miller
 había predicho el evento errado para aquel día. Ellos se convencieron
de que la profecía bíblica preveía no el retorno de Jesús a la Tierra en
 1844, pero que El comenzaría en aquella fecha un ministerio especial en
 el cielo para Sus seguidores. Así, ellos continuaron a esperar por el
breve retorno de Jesús, como hacen los Adventistas del Séptimo Día aun
hoy. <br><br>De este pequeño grupo que se rehusó a desistir después del
gran Chasco, surgieron varios líderes que construyeron la base de lo que
 vendría a ser la Iglesia Adventista del Séptimo Día. Se destacan dentro
 de estos líderes una pareja joven – Santiago y Elena White - y un
capitán de navío jubilado, Jose Bates. <br><br>Este pequeño núcleo de
“adventistas” comenzó a crecer - principalmente en los estados de la
Nueva Inglaterra en la América del Norte - adonde el movimiento de
Miller había comenzado. Elena White, apenas una adolescente en la época
del gran Chasco, se desenvolvió en una dotada escritora, oradora y
administradora, tornandose,y permaneciendo, la consejera espiritual de
confianza de la familia Adventista por mas de 70 años hasta su muerte en
 1915. Los primeros adventistas vinieron a creer - como los Adventistas
desde entonces - que ella disfruto de la dirección especial de Dios
mientras ella escribía sus consejos para el creciente grupo de
creyentes. <br><br>En 1860, en Battle Creek, Michigan, EUA, un puñado de
 congregaciones de Adventistas escogieron el nombre Adventista del
Séptimo Dia y en 1863 organizaron formalmente el cuerpo de la Iglesia
con un número de 3.500 miembros. En el principio, la actuación fue en
gran parte limitada en América del Norte, hasta 1874 cuando el primer
misionero de la Iglesia John Nevins Andrews, fue enviado para Suiza. La
obra en África fue iniciada tímidamente en 1879 cuando Dr. H. P. Ribton,
 un reciente converso en Italia, se cambio para Egipto y abrió una
escuela, pero el proyecto termino cuando tumultos comenzaron a surgir en
 los barrios. El primer pais cristiano no protestante en recibir la
iglesia fue Rusia, adonde un ministro adventista fue enviado en 1886.
Misioneros adventistas entraron por primera vez en países no cristianos
en 1894- Costa Dorada (Gana), oeste de África, y Matalbeleland, África
del Sur. En el mismo año misioneros vinieron a América del Sur, y en
1896 había representantes en Japón. La iglesia hoy tiene actuación
establecida en 209 países. <br><br>La publicación y distribución de
literaturas fueron los principales factores en el crecimiento del
movimiento del Advenimiento. La ‘Advent Review' y el ‘Sabbath Herald'
(hoy ‘Adventist Review'), órgano general de comunicación de la Iglesia,
fueron lanzados en Paris, Maine, en 1850; el ‘Youth's Instructor' en
Rochester, Nueva York, en 1852; y el&nbsp;‘Signs of the Times' en
Oakland, Califórnia, en 1874. La primera Casa Publicadora denominacional
 en Battle Creek, Michigan, comenzó a operar en 1855 y fue debidamente
incorporada en 1861 con el nombre de Asociación de Publicación
Adventista del Séptimo Día. <br><br></p>
<p align="justify">El Instituto de Reforma de la Salud, conocido mas
tarde como Sanatorio Battle Creek, abrio sus puertas en 1866, y la obra
de la sociedad misionera fue establecida a nivel estatal en 1872, y 1877
 vio la formación de las Asociaciones de las Escuelas Sabáticas en todo
el Estado. En 1903, la sede de la denominación se cambio de Battle
Creek, Michigan, para Washington, D.C., y en 1989 para Silver Spring,
Maryland, a donde ella continua a formar el nervio central del trabajo
siempre en expansión.</p>

    </div>
</div>

<!-- sidebar -->
<?php echo $this->partial('sidebar_news.phtml');?>
<!-- ENDS sidebar -->