<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/jquery-lightbox/js/jquery.lightbox-0.5.min.js","text/javascript");?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/js/lib/jquery-lightbox/css/jquery.lightbox-0.5.css");?>

<div id="page-title">
	<span class="title">Nuestro logo</span>
	<span class="subtitle">La Iglesia adventista del septimo dia y nuestro logo</span>
</div>

<!-- Posts -->
<div id="posts">
    <!-- post -->
    <div class="post">
        <div id="gallery">
            <ul>
                <li>
                    <a href="/image/logos/logo-iasd7.png" title="Logo de Iglesia Adventista del septimo dia">
                        <img alt="our logo" src="/image/logos/logo-iasd7.png" width="200" height="190">
                    </a>
                </li>
            </ul>
        </div>

        <a href="http://www.upavision.com/Escuela%20Sabatica/Cuarto%20Trimestre/Leccion05/SANTUARIO_05.pptx">Lecci<span lang="es-do">ó</span>n5 en Power Point.</a>
        <a href="/image/eess/2013/fourth_quarter/lesson05/vm2013t405.jpg" target="_blank">
            <img width="422" height="395" alt="Versículo de memoria, lección 5" src="/image/eess/2013/fourth_quarter/lesson05/vm2013t405.jpg">
        </a>

    <a target="_blank" href="http://www.micop.org./apadilla/escuela_sabatica/2013/4/ppt/leccion_05_IV_2013.ppt" sl-processed="1"><strong>Descargue el archivo completo AQUÍ: PPT</strong></a>

<!--     <iframe width="468" height="384" src="http://www.slideshare.net/slideshow/embed_code/27580242"></iframe> -->
    <iframe src="http://www.slideshare.net/slideshow/embed_code/27744337" width="468" height="384" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC;border-width:1px 1px 0;margin-bottom:5px" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="https://www.slideshare.net/jrvictor/leccion-05-iv-2013-el-santuario-la-expiacion-ofrenda-de-purificacion" title="leccion 05 IV 2013 El SANTUARIO: La Expiacion: Ofrenda de Purificacion" target="_blank">leccion 05 IV 2013 El SANTUARIO: La Expiacion: Ofrenda de Purificacion</a> </strong> from <strong><a href="http://www.slideshare.net/jrvictor" target="_blank">Victor Reynaldo Villca Villca</a></strong> </div>

    <iframe src="http://www.slideshare.net/slideshow/embed_code/27733304" width="468" height="384" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC;border-width:1px 1px 0;margin-bottom:5px" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="https://es.slideshare.net/jrvictor/leccion-escuela-sabatica-santuario-05-la-expiacin-ofrenda-de-purificacin" title="Leccion Escuela Sabatica Santuario 05: LA EXPIACIÓN: OFRENDA DE PURIFICACIÓN " target="_blank">Leccion Escuela Sabatica Santuario 05: LA EXPIACIÓN: OFRENDA DE PURIFICACIÓN </a> </strong> from <strong><a href="http://www.slideshare.net/jrvictor" target="_blank">Victor Reynaldo Villca Villca</a></strong> </div>
    </div>
</div>

<script type="text/javascript">
	$(function() {
    	$('#gallery a').lightBox();
	});
</script>