<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/jquery-lightbox/js/jquery.lightbox-0.5.min.js","text/javascript");?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/js/lib/jquery-lightbox/css/jquery.lightbox-0.5.css");?>

<div id="page-title">
	<span class="title">Nuestro logo</span>
	<span class="subtitle">La Iglesia adventista del septimo dia y nuestro logo</span>
</div>

<!-- Posts -->
<div id="posts">
    <!-- post -->
    <div class="post">
        <div id="gallery">
            <ul>
                <li>
                    <a href="/image/logos/logo-iasd7.png" title="Logo de Iglesia Adventista del septimo dia">
                        <img alt="our logo" src="/image/logos/logo-iasd7.png" width="200" height="190">
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<script type="text/javascript">
	$(function() {
    	$('#gallery a').lightBox();
	});
</script>

<!-- sidebar -->
<?php echo $this->partial('sidebar_news.phtml');?>
<!-- ENDS sidebar -->