<?php

namespace Model\Proxies\__CG__\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Club extends \Model\Club implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'name', 'description', 'street', 'neighborhood', 'zone', 'email', 'phone', 'phonemobil', 'dateInaguration', 'countMember', 'countUnityMen', 'countUnityWomen', 'countMemberDirective', 'flags', 'mastils', 'handbooks', 'banners', 'tents', 'bookMembers', 'observation', 'dateRegistre', 'areaId', 'area', 'churchId', 'church', 'pastorId', 'pastor', 'departmentId', 'department', 'id', 'created', 'changed', 'createdBy', 'changedBy', 'state');
        }

        return array('__isInitialized__', 'name', 'description', 'street', 'neighborhood', 'zone', 'email', 'phone', 'phonemobil', 'dateInaguration', 'countMember', 'countUnityMen', 'countUnityWomen', 'countMemberDirective', 'flags', 'mastils', 'handbooks', 'banners', 'tents', 'bookMembers', 'observation', 'dateRegistre', 'areaId', 'area', 'churchId', 'church', 'pastorId', 'pastor', 'departmentId', 'department', 'id', 'created', 'changed', 'createdBy', 'changedBy', 'state');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Club $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet', array());

        return parent::getStreet();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreet($street)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreet', array($street));

        return parent::setStreet($street);
    }

    /**
     * {@inheritDoc}
     */
    public function getNeighborhood()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNeighborhood', array());

        return parent::getNeighborhood();
    }

    /**
     * {@inheritDoc}
     */
    public function setNeighborhood($neighborhood)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNeighborhood', array($neighborhood));

        return parent::setNeighborhood($neighborhood);
    }

    /**
     * {@inheritDoc}
     */
    public function getZone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZone', array());

        return parent::getZone();
    }

    /**
     * {@inheritDoc}
     */
    public function setZone($zone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZone', array($zone));

        return parent::setZone($zone);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhonemobil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhonemobil', array());

        return parent::getPhonemobil();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhonemobil($phonemobil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhonemobil', array($phonemobil));

        return parent::setPhonemobil($phonemobil);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateInaguration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateInaguration', array());

        return parent::getDateInaguration();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateInaguration($dateInaguration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateInaguration', array($dateInaguration));

        return parent::setDateInaguration($dateInaguration);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountMember()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountMember', array());

        return parent::getCountMember();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountMember($countMember)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountMember', array($countMember));

        return parent::setCountMember($countMember);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountUnityMen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountUnityMen', array());

        return parent::getCountUnityMen();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountUnityMen($countUnityMen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountUnityMen', array($countUnityMen));

        return parent::setCountUnityMen($countUnityMen);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountUnityWomen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountUnityWomen', array());

        return parent::getCountUnityWomen();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountUnityWomen($countUnityWomen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountUnityWomen', array($countUnityWomen));

        return parent::setCountUnityWomen($countUnityWomen);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountMemberDirective()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountMemberDirective', array());

        return parent::getCountMemberDirective();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountMemberDirective($countMemberDirective)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountMemberDirective', array($countMemberDirective));

        return parent::setCountMemberDirective($countMemberDirective);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlags()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlags', array());

        return parent::getFlags();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlags($flags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlags', array($flags));

        return parent::setFlags($flags);
    }

    /**
     * {@inheritDoc}
     */
    public function getMastils()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMastils', array());

        return parent::getMastils();
    }

    /**
     * {@inheritDoc}
     */
    public function setMastils($mastils)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMastils', array($mastils));

        return parent::setMastils($mastils);
    }

    /**
     * {@inheritDoc}
     */
    public function getHandbooks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHandbooks', array());

        return parent::getHandbooks();
    }

    /**
     * {@inheritDoc}
     */
    public function setHandbooks($handbooks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHandbooks', array($handbooks));

        return parent::setHandbooks($handbooks);
    }

    /**
     * {@inheritDoc}
     */
    public function getBanners()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBanners', array());

        return parent::getBanners();
    }

    /**
     * {@inheritDoc}
     */
    public function setBanners($banners)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBanners', array($banners));

        return parent::setBanners($banners);
    }

    /**
     * {@inheritDoc}
     */
    public function getTents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTents', array());

        return parent::getTents();
    }

    /**
     * {@inheritDoc}
     */
    public function setTents($tents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTents', array($tents));

        return parent::setTents($tents);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookMembers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookMembers', array());

        return parent::getBookMembers();
    }

    /**
     * {@inheritDoc}
     */
    public function setBookMembers($bookMembers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBookMembers', array($bookMembers));

        return parent::setBookMembers($bookMembers);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservation', array());

        return parent::getObservation();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservation($observation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservation', array($observation));

        return parent::setObservation($observation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateRegistre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateRegistre', array());

        return parent::getDateRegistre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateRegistre($dateRegistre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateRegistre', array($dateRegistre));

        return parent::setDateRegistre($dateRegistre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPastor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPastor', array());

        return parent::getPastor();
    }

    /**
     * {@inheritDoc}
     */
    public function setPastor($pastor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPastor', array($pastor));

        return parent::setPastor($pastor);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartment', array());

        return parent::getDepartment();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartment($department)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartment', array($department));

        return parent::setDepartment($department);
    }

    /**
     * {@inheritDoc}
     */
    public function getArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArea', array());

        return parent::getArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setArea($area)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArea', array($area));

        return parent::setArea($area);
    }

    /**
     * {@inheritDoc}
     */
    public function getChurch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChurch', array());

        return parent::getChurch();
    }

    /**
     * {@inheritDoc}
     */
    public function setChurch($church)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChurch', array($church));

        return parent::setChurch($church);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getChanged()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChanged', array());

        return parent::getChanged();
    }

    /**
     * {@inheritDoc}
     */
    public function setChanged($changed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChanged', array($changed));

        return parent::setChanged($changed);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getChangedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChangedBy', array());

        return parent::getChangedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setChangedBy($changedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChangedBy', array($changedBy));

        return parent::setChangedBy($changedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', array());

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', array($state));

        return parent::setState($state);
    }

}
