<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/js/lib/jquery-ui-multiselect-widget/jquery.multiselect.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/js/lib/jquery-ui-multiselect-widget/jquery.multiselect..filter.css"); ?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/jquery-ui-multiselect-widget/src/jquery.multiselect.min.js");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/jquery-ui-multiselect-widget/src/jquery.multiselect.filter.min.js");?>

<!-- title -->
<div id="page-title">
	<span class="title"><?php echo _('Ficha de Registro Individual')?></span>
	<span class="subtitle"><?php echo _('Registrar Directivo')?></span>
</div>
<!-- ENDS title -->

<!-- Posts -->
<div id="posts">
	<!-- post -->
	<div class="post">
		<div class="thumb-shadow">
		<!-- form -->
		<?php echo $this->form;?>
		</div>
	</div>
	<!-- ENDS post -->
</div>
<!-- ENDS Posts -->

<!-- sidebar -->
<?php echo $this->partial('sidebar_registration.phtml');?>
<!-- ENDS sidebar -->

<script type="text/javascript">
$("#classConqueror").multiselect().multiselectfilter();
</script>