<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/js/lib/jquery-ui-multiselect-widget/jquery.multiselect.css"); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/js/lib/jquery-ui-multiselect-widget/jquery.multiselect..filter.css"); ?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/jquery-ui-multiselect-widget/src/jquery.multiselect.min.js");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/jquery-ui-multiselect-widget/src/jquery.multiselect.filter.min.js");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/blueimp-Load-Image/load-image.min.js","text/javascript"); ?>

<!-- title -->
<div id="page-title">
    <span class="title"><?php echo _('Registrar Directivo')?></span>
	<span class="subtitle"><?php echo _('Ficha de Registro Individual')?></span>
</div>
<!-- ENDS title -->

<!-- Posts -->
<div id="posts">
	<!-- post -->
	<div class="post">
		<div class="thumb-shadow">
		<!-- form -->
		<?php echo $this->form;?>
		</div>
	</div>
	<!-- ENDS post -->
</div>
<!-- ENDS Posts -->

<!-- sidebar -->
<?php echo $this->partial('sidebar_registration.phtml');?>
<!-- ENDS sidebar -->

<script type="text/javascript">
$(document).ready(function() {
	var result = $('#result'),
		load = function (e) {
		e = e.originalEvent;
		e.preventDefault();
		window.loadImage(
			(e.dataTransfer || e.target).files[0],
			function (img) {
				result.children().replaceWith(img);
			},
			{
			maxWidth: result.children().outerWidth(),
			canvas: true
			}
		);
	};

	$('#file-input').change(load);
});
$("#classConqueror").multiselect().multiselectfilter();
$('#dateOfBirth').datepicker({dateFormat: 'dd-mm-yy', changeMonth: true, changeYear: true, yearRange: '-100:+0'});

$("#mission").change(function () {
	this.missionId = $("#mission").val();

	// Sends request by ajax
	$.ajax({
	url: '<?php echo $this->url(array('controller'=>'Registration', 'action'=>'ds-region'));?>',
	type: "POST",
	dataType: 'json',
	data: {'missionId' : this.missionId },
	beforeSend: function(XMLHttpRequest) {
		return true;
	},

	success: function(data, textStatus, XMLHttpRequest) {
		// Removes all options for the select box
		$('#region option').remove();
		// .each loops through the array
		$.each(data.regionsArray, function(i) {
			$('#region').append($("<option></option>")
				.attr("value", i)
				.text(data.regionsArray[i]));
		});
	},

	complete: function(jqXHR, textStatus) {},

	error: function(jqXHR, textStatus, errorThrown) {}
    });
});

$("#region").change(function () {
	this.regionId = $("#region").val();

	// Sends request by ajax
	$.ajax({
	url: '<?php echo $this->url(array('controller'=>'Registration', 'action'=>'ds-district'));?>',
	type: "POST",
	dataType: 'json',
	data: {'regionId' : this.regionId },
	beforeSend: function(XMLHttpRequest) {
		return true;
	},

	success: function(data, textStatus, XMLHttpRequest) {
		// Removes all options for the select box
		$('#district option').remove();
		// .each loops through the array
		$.each(data.districtsArray, function(i) {
			$('#district').append($("<option></option>")
				.attr("value", i)
				.text(data.districtsArray[i]));
		});
	},

	complete: function(jqXHR, textStatus) {},

	error: function(jqXHR, textStatus, errorThrown) {}
    });
});

$("#district").change(function () {
	this.districtId = $("#district").val();

	// Sends request by ajax
	$.ajax({
	url: '<?php echo $this->url(array('controller'=>'Registration', 'action'=>'ds-church'));?>',
	type: "POST",
	dataType: 'json',
	data: {'districtId' : this.districtId },
	beforeSend: function(XMLHttpRequest) {
		return true;
	},

	success: function(data, textStatus, XMLHttpRequest) {
		// Removes all options for the select box
		$('#church option').remove();
		// .each loops through the array
		$.each(data.churchesArray, function(i) {
			$('#church').append($("<option></option>")
				.attr("value", i)
				.text(data.churchesArray[i]));
		});
	},

	complete: function(jqXHR, textStatus) {},

	error: function(jqXHR, textStatus, errorThrown) {}
    });
});
</script>