<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/Directive.js","text/javascript");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/blueimp-Load-Image/load-image.min.js","text/javascript"); ?>

<div style="margin:20px;">
    <br><br>
	<?php echo $this->tableHeader('filterHeader', _('Buscador'));?>
	<div id="containerFormFilter">
		<?php echo $this->formFilter;?>
	</div>
	<br>
	<?php echo $this->tableHeader('directiveHeader', _('Lista de Directivos'));?>
	<?php echo $this->tableList("tblDirective");?>
	<br>
	<br>
	<div class="buttons right">
		<?php echo $this->buttonAdd('add', $this->translate('Registrar'), $this->url(array('action'=>'add')));?>
		<?php echo $this->buttonRemove("delete-directive", $this->translate('Eliminar'), $this->url(array('action'=>'delete')));?>
	</div>

	<div id="dialog"><!-- Loads ajax dialog form --></div>
</div>
<?php //echo $this->imagelogo;?>
<script type="text/javascript">
	$(document).ready(function() {
	var directive = new com.em.Directive();

	// network
	directive.setUrl({
		toTable : '<?php echo $this->url(array('action'=>'read-items'));?>',
		toBase : '<?php echo $this->baseUrl(); ?>',
		toUpdate : '<?php echo $this->url(array('action'=>'edit')); ?>',
		toAutocomplete : '<?php echo $this->url(array('action'=>'autocomplete'));?>'
	});

	var headers = new Object();
	headers.headerArray = new Array(
		'<?php echo $this->translate('Nombre')?>',
		'<?php echo $this->translate('Celular')?>',
		'<?php echo $this->translate('Cargo')?>',
		'<?php echo $this->translate('Liderazgo')?>',
		'<?php echo $this->translate('Club')?>',
		'<?php echo $this->translate('Area de Liderazgo')?>',
		'<?php echo $this->translate('Iglesia')?>',
		'<?php echo $this->translate('Distrito')?>');
	directive.setHeaders(headers);
	// configuration of widgets
	directive.configureTable('#tblDirective', true);

	// CRUD
	directive.clickToAdd('#create-directive');
	directive.clickToUpdate('#tblDirective a[id^=update-directive-]');
	directive.clickToDelete('#delete-directive');
	directive.configureAuto('input#nameFilter');
});
</script>