<div id="dialog-form" title="<?php echo $this->translate('Edit Picture'); ?>" class="header" style="display: none;">
	<?php echo $this->form; ?>
</div>

<script type="text/javascript">
	com.em.Picture.prototype.dialogButtons = {
		'<?php echo $this->translate('Update'); ?>': function() {
			$.ajax({
				url: '<?php echo $this->url(array('module'=>'admin', 'controller'=>'Picture', 'action'=>'edit-save')); ?>',
				type: "POST",
				dataType: 'json',
				data: $('#formId').serialize(),
				beforeSend: function(XMLHttpRequest) {
					validator.form();
					if (!validator.valid()) {
						com.em.Picture.prototype.flashError('<?php echo _("The form contains error and is not updated");?>', {header: com.em.Alert.ERROR});
						return false;
					}

					com.em.Picture.prototype.processingDisplay(true);
					return true;
				},

				success: function(data, textStatus, XMLHttpRequest) {
					if (textStatus == 'success') {
						if (data.success) {
							dialogForm.dialog('close');
							table.fnDraw();
							com.em.Picture.prototype.flashSuccess(data.message, {header: com.em.Alert.SUCCESS});
						} else {
							if (data.title_duplicate) {
								$("#title").parent().find('.error').remove();
								$("#title").parent().append('<label class="error" for="title" generated="true">'+data.message+'</label>');
							} else {
								var title = data.messageArray.name;

								if (title != undefined) {
									$('#title').parent().find('.error').remove();
									$('#title').parent().append('<label class="error" for="title" generated="true">'+title.isEmpty+'</label>');
								}
							}
							com.em.Picture.prototype.flashError(data.message, {header: com.em.Alert.ERROR});
						}
					}
				},

				complete: function(jqXHR, textStatus) {
					com.em.Picture.prototype.processingDisplay(false);
				},

				error: function(jqXHR, textStatus, errorThrown) {
					dialogForm.dialog('close');
					com.em.Picture.prototype.flashError(errorThrown, {header: com.em.Alert.ERROR});
				}
			});
		},

		'<?php echo $this->translate('Cancel'); ?>': function() {
			$(this).dialog("close");
		}
	};
</script>