<div id="dialog-form" title="<?php echo $this->translate('Edit Picture'); ?>" class="header" style="display: none;">
	<?php echo $this->form; ?>
</div>

<script type="text/javascript">
	com.em.Picture.prototype.dialogButtons = {
		'<?php echo $this->translate('Update'); ?>': function() {
		    $('#formId').submit();
		},

		'<?php echo $this->translate('Cancel'); ?>': function() {
			$(this).dialog("close");
		}
	};
</script>