<div id="dialog-form" title="<?php echo $this->translate('Edit Administrator'); ?>" class="header" style="display: none;">
	<?php echo $this->form;?>
</div>

<script type="text/javascript">
	com.em.Directive.prototype.dialogButtons = {
		'<?php echo $this->translate('Edit'); ?>': function() {
			$('#formId').submit();
		},

		'<?php echo $this->translate('Cancel'); ?>': function() {
			$(this).dialog("close");
		}
	};
</script>